### ISSUE TITLE
Share should include lives left

### ISSUE THREAD

**Issue by tmarkov** [spbyrne/Murdle#3]
Since this game about suing as little missing letters as possible, not making as little guesses as possible, the "share" button should include how many lives we left at the end.

**Comment by coryveilleux** [comment]
I agree. I often reuse the same letters multiple times where possible in order to determine the correct placement of any letters that are in the word but in the wrong place. Then I'll introduce a single new character at a time. So I usually end up with double digits for the number of guesses just to avoid losing too many lives at once.

I can put together a pull request for this.

What should it look like?

## All lives in one row

💀MURDLE #320 5

❤️❤️❤️💀💀💀💀💀💀💀
🟩🟩🟩🟩🟩
⬛⬛⬛⬛🟨
⬛⬛⬛⬛🟨
🟨⬛⬛⬛⬛
⬛⬛🟨🟨🟨

## Wrapped lives to line up with grid

💀MURDLE #320 5

❤️❤️❤️💀💀
💀💀💀💀💀
🟩🟩🟩🟩🟩
⬛⬛⬛⬛🟨
⬛⬛⬛⬛🟨
🟨⬛⬛⬛⬛
⬛⬛🟨🟨🟨

## Abbreviated numbered lives

💀MURDLE #320 5

3 ❤️ / 7 💀
🟩🟩🟩🟩🟩
⬛⬛⬛⬛🟨
⬛⬛⬛⬛🟨
🟨⬛⬛⬛⬛
⬛⬛🟨🟨🟨

Something else?

@spbyrne ☝️
